version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.9.1
    working_directory: ~/repo
    branches:
      only:
        - dev-change-to-2020
    steps:
      - checkout
      - run:
          name: Npm install (node_modules directory)
          command: npm install
      - run:
          name: Git config user.email command
          command: git config --global user.email "contact@conference-agile.org"
      - run:
          name: Git config user.name command
          command: git config --global user.name "AgileFrance deployment bot"
      - add_ssh_keys:
          fingerprints:
            - "85:f9:df:ba:51:7f:92:87:fd:24:1c:55:a9:06:15:11"
      - deploy:
          name: Deployment by gulp deploy task
          command: npm run deploy