version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.9.1
    working_directory: ~/repo
    branches:
      only:
        - dev-change-to-2020
    steps:
      - checkout
      - run:
          name: Npm install (node_modules directory)
          command: npm install
      - run:
          name: Git config user.email command
          command: git config --global user.email "contact@conference-agile.org"
      - run:
          name: Git config user.name command
          command: git config --global user.name "AgileFrance deployment bot"
      - add_ssh_keys:
          fingerprints:
            - "79:b7:d9:fa:15:e8:c3:23:39:63:13:48:36:57:f4:f8"
      - deploy:
          name: Deployment by gulp deploy task
          command: npm run deploy